version: 2.1

jobs:
  deps-n-test:
    docker:
    - image: circleci/node:14-buster
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
    - run: npm ci
    - save_cache:
        paths: ~/.npm
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run: npm run lint -- --no-fix
    - run: npm run build
    - run: npm test
    - store_artifacts:
        path: coverage
    - persist_to_workspace:
        root: .
        paths: '*'

  deploy-to-npm:
      docker:
      - image: circleci/node:14-buster
      steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" > ~/.npmrc
      - run: npm publish

envs-matcher:
  build: &build
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/

  deploy: &deploy
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v?\d+\.\d+\.\d+(-\d+)?$/

workflows:
  build_n_test_n_deploy:
    jobs:
    - deps-n-test:
        <<: *build
    - deploy-to-npm:
        <<: *deploy
        requires:
        - deps-n-test
