name: Install deps


runs:
  using: 'composite'

  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    
    # Cache future Node Dep
    - name: Cache Node dependencies
      id: cache-node
      uses: actions/cache@v2
      with:
        path: ./.npm
        key: v1-dependencies-{{ checksum "package-lock.json" }}

  # If 'package-lock.json' is the same as the key cache
  # Do not npm install ;)
    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::INSTALL NPM DEPS"
        if [ "${{ steps.cache-node.outputs.cache-hit }}" != "true" ];  then
          echo "No cache : run npm install"
          npm install
        else
          echo "Use cache Node from a previous build."
        fi
        echo "::endgroup::"