name: Build & publish lib to NPM

on:
  workflow_dispatch:
  
  push:
    tags: ["*"]

jobs:    
  publish: 
    name: Publish to NPM 
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install Deps
        run: npm ci
      
      - name: Lint
        run: npm run lint -- --no-fix
      
      - name: Build
        run: npm run build
      
      - name: Publish 
        shell: bash
        run: |
          export NPM_TOKEN=${{ env.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

          if ${{ !startsWith(github.ref, 'refs/tags/') }}; then
            npm version prerelease --git-tag-version false --preid=${{ github.sha }}
          fi

          npm publish
    
